```{r}
# Installing heimdall
install.packages("heimdall")
```

```{r}
# Loading heimdall
library(daltoolbox)
library(heimdall) 
```

```{r}
# ADWIN Drifter Example
# This example uses an distribuition-based drift detector with a synthetic variable.
seed <- 1
set.seed(seed)
```

```{r}
# Load Data

data(st_drift_examples)
serie <- st_drift_examples$univariate
```

```{r}
# Plot Serie

plot(x=rownames(serie), y=serie[['serie']])
```

```{r}
# Instantiate Model

model <- dfr_adwin(target_feat='serie')
```

```{r}
# Detection

detection <- NULL
output <- list(obj=model, drift=FALSE)
for (i in 1:length(serie$serie)){
 output <- update_state(output$obj, serie$serie[i])
 if (output$drift){
   type <- 'drift'
   output$obj <- reset_state(output$obj)
 }else{
   type <- ''
 }
 detection <- rbind(detection, data.frame(idx=i, event=output$drift, type=type))
}
```

```{r}
# Plot Drifts

detection[detection$type == 'drift',]
```

```{r}
plot(x=rownames(serie), y=serie[['serie']])
for(drift_index in detection[detection$type == 'drift', 'idx']){
  abline(v=drift_index, col='red', lty=2)
}
```
